
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'aw_project_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'aw_project_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
models:
  aw_project_dbt:
    01_staging:
      +materialized: ephemeral
      +schema: staging
    02_intermediate:
      +materialized: table
      +schema: intermediate
    03_marts:
      +materialized: table
      +schema: marts
