aw_project_dbt:
  outputs:
    dev:
      catalog: "{{ env_var('DBT_CATALOG') }}"
      host: "{{ env_var('DBT_HOST') }}" 
      http_path: "{{ env_var('DBT_HTTP_PATH') }}" 
      schema: "{{ env_var('DBT_SCHEMA') }}"   
      threads: 1
      token: "{{ env_var('DBT_TOKEN') }}"
      type: databricks
  target: dev
